# Generated by Django 5.2.7 on 2026-09-08 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spaceimage',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spaces.space'),
        ),
        migrations.AddField(
            model_name='spacetype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_types', to='spaces.category'),
        ),
        migrations.AddField(
            model_name='space',
            name='space_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spaces', to='spaces.spacetype'),
        ),
    ]
