# Generated by Django 5.2.7 on 2026-09-23 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def populate_category_slugs(apps, schema_editor):
    Category = apps.get_model("spaces", "Category")

    for category in Category.objects.all():
        category.slug = slugify(category.name)
        category.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('institution_type', models.CharField(choices=[('university', 'University'), ('college', 'College'), ('polytechnic', 'Polytechnic'), ('institute', 'Institute'), ('other', 'Other')], default='university', max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('campus', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentAccommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(blank=True, max_length=150)),
                ('distance_to_campus_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('room_type', models.CharField(choices=[('private_room', 'Private Room'), ('shared_room', 'Shared Room'), ('entire_unit', 'Entire Unit')], default='private_room', max_length=20)),
                ('rooms_available', models.PositiveIntegerField(default=1)),
                ('bathroom_type', models.CharField(blank=True, choices=[('private', 'Private Bathroom'), ('shared', 'Shared Bathroom')], max_length=10, null=True)),
                ('meal_plan', models.CharField(choices=[('none', 'No Meals'), ('optional', 'Meals Available'), ('included', 'Meals Included')], default='none', max_length=10)),
            ],
            options={
                'verbose_name': 'Student Accommodation',
                'verbose_name_plural': 'Student Accommodations',
            },
        ),
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['province', 'city', 'area']},
        ),
        migrations.AlterModelOptions(
            name='space',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='spacetype',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(
                blank=True,
                max_length=100,
                db_index=False,
            ),
        ),
        
        migrations.RunPython(
            code=populate_category_slugs,
            reverse_code=migrations.RunPython.noop,
        ),
        
        migrations.AddField(
            model_name='space',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('ZiG', 'Zimbabwe Gold')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='space',
            name='listing_purpose',
            field=models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], default='rent', max_length=10),
        ),
        migrations.AddField(
            model_name='space',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Verification Pending'), ('verified', 'Verified'), ('rejected', 'Verification Rejected')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='space',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='space',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='space',
            name='rental_period',
            field=models.CharField(blank=True, choices=[('hour', 'Per Hour'), ('day', 'Per Day'), ('week', 'Per Week'), ('month', 'Per Month'), ('year', 'Per Year')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['city'], name='spaces_loca_city_6244c9_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['area'], name='spaces_loca_area_0a99a4_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['province'], name='spaces_loca_provinc_405285_idx'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['category'], name='spaces_spac_categor_551dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['space_type'], name='spaces_spac_space_t_1f6d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['location'], name='spaces_spac_locatio_1f1e09_idx'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['listing_purpose'], name='spaces_spac_listing_a1f6a7_idx'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['is_available'], name='spaces_spac_is_avai_23cfb9_idx'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['verification_status'], name='spaces_spac_verific_fd3c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['created_at'], name='spaces_spac_created_dc30d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='spacetype',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_space_type_per_category'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['city'], name='spaces_inst_city_3612bb_idx'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['institution_type'], name='spaces_inst_institu_e4f2a2_idx'),
        ),
        migrations.AddField(
            model_name='studentaccommodation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_accommodations', to='spaces.institution'),
        ),
        migrations.AddField(
            model_name='studentaccommodation',
            name='space',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_details', to='spaces.space'),
        ),
        migrations.AddIndex(
            model_name='studentaccommodation',
            index=models.Index(fields=['institution'], name='spaces_stud_institu_4d7a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentaccommodation',
            index=models.Index(fields=['room_type'], name='spaces_stud_room_ty_fc2324_idx'),
        ),
        migrations.AddIndex(
            model_name='studentaccommodation',
            index=models.Index(fields=['distance_to_campus_km'], name='spaces_stud_distanc_11cd04_idx'),
        ),
    ]
