# Generated by Django 5.2.7 on 2026-09-29 23:21

import rentspace.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceimage',
            name='image',
            field=models.ImageField(storage=rentspace.storage_backends.SupabaseStorage(), upload_to='space_images/'),
        ),
    ]
